<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AgendamentoConsultas.Domain\AgendamentoConsultas.Domain.csproj" />
    <ProjectReference Include="..\AgendamentoConsultas.Application\AgendamentoConsultas.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
